create documentation pipeline to sync control documentation
kubescape/kubescape.io pull request #31
Opened 2023-11-21 13:04 UTC by TRohit20

As part of the LFX mentorship, creating a documentation pipeline to automatically generate and update the controls library documentation.

- Adding two actions to auto-approve and merge pull request from `kubescape` syncing the documentation changes every release.
- The actions are only triggered when PR is from `kubescape` and ignores any other pull requests. 
- Pull request is merged automatically if all checks pass.

2023-11-22 01:42 UTC, craigbox commented
Please also add sufficient documentation (a) in comments in each file (b) in a page on https://github.com/kubescape/kubescape.io/wiki which refers to how the workflow works overall.

(You should have reference to this in the docs you put on the regolibrary repo also.)

2023-11-28 15:01 UTC, matthyx requested changes
can you document the use case here and be specific on why we need all these?

2023-11-28 15:34 UTC, TRohit20 commented on .github/workflows/auto-merge.yml
> +  # Events which trigger the action on the pull request
Well, you are right. We can just use 'labelled' and 'completed' to trigger the action. Shall I remove the redundant triggers?

2023-11-28 15:34 UTC, TRohit20 commented on .github/workflows/auto-merge.yml
> +      - completed  # when all checks for a pull request are completed
We sure can just run on 'completed' because all checks complete means also the approval.

2023-12-13 11:35 UTC, TRohit20 commented on .github/workflows/auto-merge.yml
> +  # Events which trigger the action on the pull request
Checked, tested and works the same as expected.

2023-12-13 11:36 UTC, TRohit20 commented on .github/workflows/auto-merge.yml
> +      - completed  # when all checks for a pull request are completed
Done, I have removed all the redundant events, put only the ones that are necessary and tested the workflow, you can have a look at the [test PR here](https://github.com/TRohit20/kubescape.io/pull/19).

2024-05-06 06:20 UTC, matthyx approved these changes

2024-05-06 06:20 UTC, merged